### ISSUE TITLE
Install Google Analytics

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_MULLINS_HVAC#13]
Once we've got the domain, I'll create an account and add you as a user. Then you can add the code to the site. I think we usually make a quick plugin or something for that. There might already be one installed that you can use. Ask your questions here.

**Comment by d4mation** [comment]
Google Analytics has been added to the site, but currently it isn't displaying as "Connected" within the Google Analytics Admin Dashboard. I'll check on it again later on and see if it has updated, then I'll close the issue.

![image width = 400px](https://cloud.githubusercontent.com/assets/7770631/10643164/63afa8f0-77ef-11e5-8c5b-4bdc925b48ae.png)

**Comment by d4mation** [comment]
Working now. It just took ages to show any actual data I guess. Normally in my experience it doesn't take so long... Imported a Custom Report to show Hourly Traffic as well because it helped me determine if it was working or not this morning.

![image width = 400px](https://cloud.githubusercontent.com/assets/7770631/10666025/17031628-789d-11e5-9632-f8a370854331.png)
