### ISSUE TITLE
New content manager role

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_MULLINS_HVAC#29]
I need a new role on the site which is basically an editor with the additional capabilities of managing options and using the customizer. Menus, widgets, etc. Not users, plugins, theme changing, etc.

Then assign the user Tricia this role.

**Comment by d4mation** [comment]
Implemented it as a Plugin so that it would have those nice Activation/Deactivation hooks.

Turns out the Customizer stuff, widgets, and menus are all tied to `edit_theme_options`, so I gave it that and all the Editor capabilities (with the exception of `unfiltered_html` as that can be nasty on a Multi Site).
