### ISSUE TITLE
Color pickers in customizer

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_MULLINS_HVAC#30]
The client has requested control over some colors, in particular the dark blue. Can we add some more options to the customizer and then let those options define the main colors used in the theme? Like the blue, red and gray? Could be like Accent Color 1, Accent Color 2, etc.

**Comment by d4mation** [comment]
The Primary Color (Blue), Secondary Color (Red) and both of the Greys are now changeable from the Customizer.

I included [phpColors](https://github.com/mexitek/phpColors) to replicate the `darken` and `lighten` SASS functions so that for small variations of color (Like for Hovering on Menu Items) we could still calculate those on-the-fly.

As a result of moving this styling to the Customizer, anything Color related is now under `includes/partials/customizer-css.php`;
