### ISSUE TITLE
Control for changing subscribe heading and text

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_MULLINS_HVAC#33]
Client wants the ability to change what the newsletter form says. Customizer control maybe? Or a more global setting?

**Comment by d4mation** [comment]
I've checked the MailChimp Plugin's code for the Widget and there's no way to set this using the Customizer (Either via a Filter or via Widget Instantiation Arguments).

There are Filters that could set them, but they require "Dev Mode" to be enabled for the Plugin, but that would likely not be wise for Production. It would need to be defined using `define('MAILCHIMP_DEV_MODE', true);`

The only way around using "Dev Mode" would be to give their User Role the `manage_options` capability so that they can access the Form on the backend. However, this can be overwritten using `define('MCSF_CAP_THRESHOLD', '<capability>');` so we could just make a random capability up to give them access. I will create a custom capability and assign it to their User Role as well as `administrator` to solve this Issue.

Here's the what the Form for setting the strings in the Dashboard looks like:
![image](https://cloud.githubusercontent.com/assets/7770631/11799306/f077f158-a2a0-11e5-9fc9-de82c82a4012.png)
