### ISSUE TITLE
Widgetize sidebar

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_MULLINS_HVAC#41]
Client was asking for the ability to rearrange the items in the right sidebar. I just observed it isn't possible for them to do. Can we make that widgetized or is there another way to edit them that I missed?

**Comment by d4mation** [comment]
The only way I could see this working for everything to be re-arrangeable would be to:
- Convert the Angie's List badge itself into a Widget (Or otherwise just have it be a Text Widget with straight HTML inside)
  - The Angie's List badge is currently generated via Customizer options
- Make a wrapper widget for/extend the MailChimp Widget, since I had to do some custom instantiation for it to look/work the way it does that wasn't available within the Add Widget Form itself.
  - `the_widget( 'mailchimpSF_Widget', 'after_widget=<div class="text-right"><a href = "#" data-reveal-id="drawing-terms-modal">Terms and Conditions</a></div>&after_title=<span class="fa fa-envelope-o alignright"></h2>');`

However, we could add a Widgetized Area above and/or below these no problem.

**Comment by brashrebel** [comment]
Hmmm...I tend to think it should function like a standard sidebar. Do you mind making that into a widgetized area with two widgets? They want to be able to rearrange the order and add something else. Also, that would align well with the UX I expected when I attempted to edit that area.

**Comment by d4mation** [comment]
I'll give it a shot. The only difficult part should be the MailChimp widget.
