### ISSUE TITLE
Leave a testimonial feature

### ISSUE THREAD

**Issue by brashrebel** [realbig/TH_MULLINS_HVAC#5]
We need a system for testimonials to be left and displayed. This should include:
- A special view somewhere on the home page where a different testimonial is displayed on each page load
- A button/link near that testimonial that says "Leave your own testimonial"
- A simple form (comment form or Gravity Form) that visitors can fill out with their feedback
- A notification sent to the site admin when testimonials need moderation

**Comment by d4mation** [comment]
I have gotten this working beautifully on my Local instance, but the WP Engine Page Caching seems to be preventing it from querying a random Testimonial on each Page Load.

What's strange is that this even happens if I'm logged in. Generally I've found the Page Caching doesn't affect me when I'm logged in.

Have any ideas? Outside of pulling every Testimonial and passing them to JavaScript to pick one randomly, I can't think of a good way around it. Relevant Query is in template-home.php.

**Comment by d4mation** [comment]
Figured out that WP Engine disables all RAND queries in MySQL for their Page Caching.

It can be disabled in the WP Engine menu in /wp-admin

![image width = 400px](https://cloud.githubusercontent.com/assets/7770631/10731698/fced3af6-7bcc-11e5-9a9f-d5a3a55a66a7.png)

(I don't have access to this. This screenshot is from another install I have access to).

**Comment by brashrebel** [comment]
This appears to be broken. Clicking the leave a testimonial link just makes the screen dim but nothing appears.

**Comment by d4mation** [comment]
I was never able to replicate this issue myself. However, given that the Testimonials are now in the header it may no longer be a problem:

![image](https://cloud.githubusercontent.com/assets/7770631/11573976/ffe86168-99d6-11e5-9449-f1c012f10ea9.png)

The Testimonial having the same image as the CTA in the screenshot is just coincidence, haha. This is my local install.

**Comment by brashrebel** [comment]
Wow. Loving where this is going. And sure, let's close for now.
